### YamlMime:FAQ
metadata:
  title: Azure 기밀 컴퓨팅 FAQ
  description: Azure 기밀 컴퓨팅에 대해 자주 묻는 질문에 대한 답변입니다.
  author: stempesta
  ms.topic: troubleshooting
  ms.workload: infrastructure
  ms.service: virtual-machines
  ms.subservice: confidential-computing
  ms.date: 11/1/2021
  ms.author: stempesta
  ms.openlocfilehash: 1a0ad11c4d73fbeb703eabca307ae4349a3457c9
  ms.sourcegitcommit: 3d04177023a3136832adb561da831ccc8e9910c7
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 11/23/2021
  ms.locfileid: "132934290"
title: Intel SGX 기밀 VM의 애플리케이션 Enclave에 대한 질문과 대답
summary: >
  이 문서에서는 [Intel SGX Azure 가상 머신에서 기밀 컴퓨팅 워크로드를](overview.md)실행하는 데 관한 가장 일반적인 질문 중 일부에 대한 답변을 제공합니다.


  Azure 문제와 관련된 정보가 이 문서에 없을 경우 [MSDN 및 Stack Overflow에서 Azure 포럼](https://azure.microsoft.com/support/forums/)을 방문합니다. 이러한 포럼이나 [@AzureSupport Twitter](https://twitter.com/AzureSupport) 의 에 문제를 게시할 수 있습니다. Azure 지원 요청을 제출할 수도 있습니다. 지원 요청을 제출하려면 [Azure 지원 페이지](https://azure.microsoft.com/support/options/)에서 지원 받기를 선택합니다.
sections:
- name: 무시됨
  questions:
  - question: >
      Azure에서 DCsv2 시리즈 VM을 배포하려면 어떻게 하나요?
    answer: "다음은 DCsv2 VM을 배포할 수 있는 몇 가지 방법입니다.\n   - [Azure Resource Manager](../virtual-machines/windows/template-description.md) 템플릿 사용\n   - [Azure Portal](https://portal.azure.com/#create/hub)에서\n   - [Azure 기밀 컴퓨팅(가상 머신)](https://azuremarketplace.microsoft.com/marketplace/apps/microsoft-azure-compute.acc-virtual-machine-v2?tab=overview) 마켓플레이스 솔루션 템플릿. 마켓플레이스 솔루션 템플릿은 고객을 지원되는 시나리오(지역, 이미지, 가용성, 디스크 암호화)로 제한하는 데 도움이 됩니다. \n"
  - question: >
      Azure에서 DCsv3 또는 DCdsv3 시리즈 VM을 배포하는 방법
    answer: "v3 Intel SGX VM은 현재 미리 보기로 제공됩니다. v2 Intel SGX VM을 배포할 수 있는 것과 동일한 방식으로 배포할 수 있습니다.\n   - [Azure Resource Manager](../virtual-machines/windows/template-description.md) 템플릿 사용\n   - [Azure Portal](https://portal.azure.com/#create/hub)에서\n   - [Azure 기밀 컴퓨팅(가상 머신)](https://azuremarketplace.microsoft.com/marketplace/apps/microsoft-azure-compute.acc-virtual-machine-v2?tab=overview) 마켓플레이스 솔루션 템플릿. 마켓플레이스 솔루션 템플릿은 고객을 지원되는 시나리오(지역, 이미지, 가용성, 디스크 암호화)로 제한하는 데 도움이 됩니다. \n"
  - question: >
      모든 OS 이미지가 Intel SGX 가상 머신에서 작동합니까?
    answer: >
      아니요. 가상 머신은 Ubuntu Server 18.04, Ubuntu Server 20.04 및 Windows Server 2019 Datacenter를 사용하는 2세대 운영 컴퓨터에만 배포할 수 있습니다. [Linux](../virtual-machines/generation-2.md) 및 [Windows](../virtual-machines/generation-2.md)에서의 Gen 2 VM에 대해 자세히 알아보세요.
  - question: >
      Intel SGX 가상 머신이 포털에서 회색으로 표시되고 하나를 선택할 수 없습니다.
    answer: "VM 옆의 정보 버블에 따라 다음과 같이 조치를 취해야 합니다.\n   -    **UnsupportedGeneration**: 가상 머신 이미지의 세대를 “Gen2”로 변경합니다.\n   -    **NotAvailableForSubscription**: 해당 지역에서 아직 구독할 수 없습니다. 사용 가능한 지역을 선택합니다.\n   -    **InsufficientQuota**: [할당량을 늘리는 지원 요청을 만듭니다](../azure-portal/supportability/per-vm-quota-requests.md). 평가판 구독에는 일부 기밀 컴퓨팅 VM에 대한 할당량이 없습니다. \n"
  - question: >
      포털 크기 선택기에서 검색하려고 하면 Intel SGX 가상 머신이 표시되지 않습니다.
    answer: "[사용 가능한 지역](https://azure.microsoft.com/global-infrastructure/services/?products=virtual-machines)을 선택했는지 확인합니다. 또한 크기 선택기에서 \"모든 필터 지우기\"를 선택해야 합니다. \n"
  - question: >
      Azure 기밀 컴퓨팅에서 Intel SGX를 사용하여 가속 네트워킹을 사용하도록 설정할 수 있나요?
    answer: 경우에 따라 다릅니다. - 가속화된 네트워킹은 DC-Series 또는 DCsv2-Series 가상 머신에서 지원되지 않습니다. 이러한 VM 크기에서 실행되는 기밀 컴퓨팅 가상 머신 배포 또는 Azure Kubernetes Service 클러스터 배포에는 가속 네트워킹을 사용하도록 설정할 수 없습니다. - 가속화된 네트워킹은 CLI 프로비저닝 및 ARM 템플릿을 통해서만 DCdsv3-Series 및 DCsv3-Series VM에서 지원됩니다.
  - question: >
      해당 머신에서 Azure Dedicated Host를 사용할 수 있나요?
    answer: "Azure Dedicated Host는 DCsv2-series 가상 머신을 지원합니다. Azure Dedicated Host는 가상 머신을 실행하는 물리적 단일 테넌트 서버를 제공합니다. 일반적으로 사용자는 Azure Dedicated Host를 사용하여 물리적 보안, 데이터 무결성 및 모니터링에 대한 규정 준수 요구 사항을 해결합니다. \n"
  - question: >
      Azure Resource Manager 템플릿 배포 실패 오류가 발생합니다. "승인된 표준 DC 제품군 코어 할당량을 초과하여 작업을 완료할 수 없습니다."
    answer: "[할당량을 늘리는 지원 요청을 만듭니다](../azure-portal/supportability/per-vm-quota-requests.md). 평가판 구독에는 일부 기밀 컴퓨팅 VM에 대한 할당량이 없습니다. \n"
  - question: >
      DCsv2 시리즈, DC 시리즈, DCdsv3-Series 및 DCsv3-Series VM의 차이점은 무엇인가요?
    answer: "- DC 시리즈 VM은 Intel SGX를 사용하는 이전 6코어 Intel 프로세서에서 실행되고, 총 메모리가 더 작고 EPC(Enclave 페이지 캐시) 메모리가 더 작고, 두 지역에서만 사용할 수 있습니다(미국 동부 및 서유럽에서 Standard_DC2s 및 Standard_DC4s). 이러한 VM을 일반 공급할 계획은 없으며 프로덕션 환경에서는 사용하지 않는 것이 좋습니다. 이러한 VM을 배포하려면 기밀 컴퓨팅 DC 시리즈 VM(미리 보기) Marketplace 인스턴스를 사용합니다.\n- DCsv2-Series VM은 8코어 Intel 프로세서에서 실행되며 더 많은 총 메모리, EPC 크기를 가지며 더 많은 지역에서 사용할 수 있습니다. 이러한 컴퓨터는 일반적으로 사용할 수 있습니다. \n- DCsv3-Series 및 DCdsv3-Series VM은 최신 세대의 Intel SGX 컴퓨터입니다. 이 세대에서 CPU 코어는 6배(최대 48개 코어까지) 증가했으며, EPC(암호화된 메모리)는 1500x에서 256GB로 증가했으며, 일반 메모리는 12배에서 384GB로 증가했습니다. 이러한 모든 변경 내용은 Gen-On-Gen 성능을 크게 향상시키고 완전히 새로운 시나리오의 잠금을 해제합니다. 이러한 VM은 Intel TME(Total Memory Encryption)도 지원합니다. 2021년 11월 1일부터 이러한 VM은 아직 공개 미리 보기로 있으며 프로덕션 용도에 적합하지 않습니다. \n- DCdsv3-Series VM은 로컬 디스크를 지원하므로 DCsv3-Series VM과 다릅니다.\n"
  - question: >
      Intel SGX 가상 머신을 전역적으로 사용할 수 있나요?
    answer: "아니요. 이번에는 일부 지역에서만 이러한 가상 머신을 사용할 수 있습니다. 사용 가능한 지역에 대한 최신 정보는 [지역별 제품 페이지](https://azure.microsoft.com/global-infrastructure/services/?products=virtual-machines)를 확인하세요. \n"
  - question: >
      해당 머신에는 하이퍼 스레딩이 해제되어 있나요?
    answer: >
      하이퍼 스레딩은 모든 Azure 기밀 컴퓨팅 Intel SGX 머신에 대해 사용하지 않도록 설정됩니다.
  - question: >
      Intel SGX 가상 머신에 Open Enclave SDK를 설치할 어떻게 할까요? 있나요?
    answer: "Azure 또는 온-프레미스 머신에 OE SDK를 설치하는 방법에 대한 지침은 [Open Enclave SDK GitHub](https://github.com/openenclave/openenclave)의 지침을 따르세요.\n     \nOpen Enclave SDK GitHub에서 OS별 설치 지침도 자세히 알아볼 수 있습니다.\n   - [Windows에 OE SDK 설치](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md)\n   - [Ubuntu 18.04에 OE SDK 설치](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md)"
