- name: Azure AD 역할 설명서
  href: index.yml
- name: 개요
  items:
    - name: Azure AD RBAC란?
      href: custom-overview.md
- name: 빠른 시작
  items:
    - name: 사용자에게 역할 할당
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: 개념
  items:
    - name: Azure AD 역할 이해
      href: concept-understand-roles.md
    - name: 역할 비교
      items:
        - name: Azure 및 Azure AD 역할 비교
          href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Microsoft 365 역할
          href: m365-workload-docs.md
    - name: 그룹을 사용하여 역할 할당 관리
      href: groups-concept.md
    - name: 관리 단위
      href: administrative-units.md
    - name: 모범 사례
      href: best-practices.md
    - name: 보안
      items:
        - name: 역할 보안 계획
          href: security-planning.md
        - name: 비상 계정 만들기
          href: security-emergency-access.md
- name: 방법 가이드
  items:
    - name: 사전 요구 사항
      href: prerequisites.md
    - name: 역할 정의 나열
      href: role-definitions-list.md
    - name: 역할 할당 나열
      items:
        - name: 역할 할당 나열
          href: view-assignments.md
        - name: 사용자에 대한 역할 할당 목록
          href: list-role-assignments-users.md
        - name: 그룹에 대한 역할 할당 나열
          href: groups-view-assignments.md
    - name: 역할 할당
      items:
        - name: 사용자에게 역할 할당
          href: manage-roles-portal.md
        - name: 다른 범위의 사용자에게 역할 할당
          href: assign-roles-different-scopes.md
        - name: 역할 할당 가능 그룹 만들기
          href: groups-create-eligible.md
        - name: 그룹에 역할 할당
          href: groups-assign-role.md
        - name: PIM에서 역할에 적합한 그룹 만들기
          href: groups-pim-eligible.md
        - name: PowerShell을 사용하여 범위가 있는 역할 할당
          href: custom-assign-powershell.md
        - name: Graph API를 사용하여 역할 할당
          href: custom-assign-graph.md
    - name: 역할 할당 제거
      items:
        - name: 그룹에서 역할 할당 제거
          href: groups-remove-assignment.md
    - name: 사용자 지정 역할 만들기
      items:
        - name: 사용자 지정 역할 만들기
          href: custom-create.md
        - name: 엔터프라이즈 앱에 대한 사용자 지정 역할 만들기
          href: custom-enterprise-apps.md
        - name: 무제한 앱 등록 만들기
          href: quickstart-app-registration-limits.md
    - name: 관리 단위
      items:
        - name: 추가 및 관리
          href: admin-units-manage.md
        - name: 사용자 추가 및 관리
          href: admin-units-add-manage-users.md
        - name: 그룹 추가 및 관리
          href: admin-units-add-manage-groups.md
        - name: 범위를 사용하여 역할 할당
          href: admin-units-assign-roles.md
    - name: 대리자
      items:
        - name: 관리 역할 위임
          href: delegate-app-roles.md
        - name: 내 직원 위임
          href: my-staff-configure.md
    - name: 문제 해결
      items:
        - name: 그룹에 할당된 역할 문제 해결
          href: groups-faq-troubleshooting.yml
        - name: 관리 단위 문제 해결
          href: admin-units-faq-troubleshoot.yml
        - name: Azure AD에 대한 지원
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: 참조
  items:
    - name: 기본 제공 역할
      href: permissions-reference.md
    - name: 태스크별 최소 권한 있는 역할
      href: delegate-by-task.md
    - name: 기본 사용자 사용 권한
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: 사용자 지정 역할
      items:
        - name: 앱 등록 권한
          href: custom-available-permissions.md
        - name: 엔터프라이즈 앱 사용 권한
          href: custom-enterprise-app-permissions.md
        - name: 앱 동의 권한
          href: custom-consent-permissions.md
    - name: Azure AD 서비스 제한
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Azure AD PowerShell
      href: /powershell/module/azuread/#directory-roles
    - name: Microsoft Graph API
      href: /graph/api/resources/directoryrole