### YamlMime:Landing
title: Azure Arc 지원 Kubernetes
summary: Azure Arc로 Kubernetes 클러스터를 관리하는 방법 알아보기
metadata:
  title: Azure Arc 지원 Kubernetes
  description: Azure에서 온-프레미스 머신을 관리하는 방법에 대해 알아보기
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: b4ab0ed6a5aa7191187040970d8b1da4ae4ebc48
  ms.sourcegitcommit: cae9bf0cad514c974c0c0185e24fd4b4b3132432
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 12/01/2021
  ms.locfileid: "133407744"
landingContent:
- title: Azure Arc 지원 Kubernetes에 대한 정보
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc 지원 Kubernetes란?
      url: overview.md
    - text: Azure Arc 유효성 검사 프로그램
      url: validation-program.md
  - linkListType: concept
    links:
    - text: 에이전트 개요
      url: conceptual-agent-overview.md
    - text: 클러스터 확장
      url: conceptual-extensions.md
    - text: 사용자 지정 위치
      url: conceptual-custom-locations.md
    - text: 구성 및 GitOps(Flux v2)
      url: conceptual-gitops-flux2.md
    - text: 질문과 대답
      url: faq.md
- title: 시작
  linkLists:
  - linkListType: quickstart
    links:
    - text: 클러스터를 Azure Arc에 연결
      url: quickstart-connect-cluster.md
- title: GitOps를 사용하여 구성 배포
  linkLists:
  - linkListType: tutorial
    links:
    - text: GitOps를 사용하여 구성 배포(Flux v2)
      url: tutorial-use-gitops-flux2.md
    - text: GitOps를 통해 CI/CD 구현(Flux v2)
      url: tutorial-gitops-flux2-ci-cd.md
- title: 클러스터 관리
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: 컨테이너용 Azure Monitor를 사용하여 모니터링
      url: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json
    - text: Microsoft Defender for Cloud를 사용하여 위협 방지 적용
      url: ../../defender-for-cloud/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json
    - text: Azure Policy를 사용한 클러스터 내 정책 시행
      url: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
    - text: Azure Arc 지원 Open Service Mesh 배포
      url: tutorial-arc-enabled-open-service-mesh.md
    - text: Azure Key Vault 비밀에 액세스
      url: tutorial-akv-secrets-provider.md
- title: 개념 증명
  linkLists:
  - linkListType: sample
    links:
    - text: 빠른 시작
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: 참조 아키텍처
  linkLists:
  - linkListType: architecture
    links:
    - text: 하이브리드 Kubernetes 클러스터의 배포 및 구성 관리
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
